// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASI_ospm57QyrZIrAR9AzvURMGwWcT-9Q',
    appId: '1:809214919230:web:2921ecc8318a865d43476f',
    messagingSenderId: '809214919230',
    projectId: 'spk-smartcity',
    authDomain: 'spk-smartcity.firebaseapp.com',
    storageBucket: 'spk-smartcity.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_MP4krEb3Ygw220pijW9i4-ElrbCG88A',
    appId: '1:809214919230:android:c2c16100b0921ae243476f',
    messagingSenderId: '809214919230',
    projectId: 'spk-smartcity',
    storageBucket: 'spk-smartcity.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIRBbDL79pSY206XE0_Zdo4WuQOVs9_hI',
    appId: '1:809214919230:ios:60bd47910b2cb7ed43476f',
    messagingSenderId: '809214919230',
    projectId: 'spk-smartcity',
    storageBucket: 'spk-smartcity.firebasestorage.app',
    iosBundleId: 'com.spk.smartcity.spkSmartcity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIRBbDL79pSY206XE0_Zdo4WuQOVs9_hI',
    appId: '1:809214919230:ios:60bd47910b2cb7ed43476f',
    messagingSenderId: '809214919230',
    projectId: 'spk-smartcity',
    storageBucket: 'spk-smartcity.firebasestorage.app',
    iosBundleId: 'com.spk.smartcity.spkSmartcity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASI_ospm57QyrZIrAR9AzvURMGwWcT-9Q',
    appId: '1:809214919230:web:b140a88680f16cc843476f',
    messagingSenderId: '809214919230',
    projectId: 'spk-smartcity',
    authDomain: 'spk-smartcity.firebaseapp.com',
    storageBucket: 'spk-smartcity.firebasestorage.app',
  );
}
